### PR TITLE
Feature entityframework

### PR DESCRIPTION
**Pull request by 587900**
Torje DAO things

### CODE REVIEW

**Review by 587900 — COMMENTED** [review]
- [x] Naming conventions on some namespaces should be changed (no underscore, single dot namespace)
- [x] Scraping should be run ahead-of-time (outside project) and store results for use in project
- [x] Do not use æ, ø, å
- [x] Choosing language should probably not utilize strings, but the enums themselves (?)
- [x] Some DAOs might be unecessary

**Review by 587851 — DISMISSED** [review]

**Review by How2sleep — DISMISSED** [review]
good stuff

**Comment by 587851** [comment]
> * [ ]  Naming conventions on some namespaces should be changed (no underscore, single dot namespace)
> 
>     * [ ]  Scraping should be run ahead-of-time (outside project) and store results for use in project
> 
>     * [ ]  Do not use æ, ø, å
> 
>     * [ ]  Choosing language should probably not utilize strings, but the enums themselves (?)
> 
>     * [ ]  Some DAOs might be unecessary

No

**Review by How2sleep — APPROVED** [review]
ok+

**Pull request merged**
